= _hl-vhost-x-01_
Jonas Fierlings <https://github.com/PigeonF[@PigeonF]>;
// settings:
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URLs:
:url-nixos-anywhere: https://github.com/nix-community/nixos-anywhere
:url-deploy-rs: https://github.com/serokell/deploy-rs

_hl-vhost-x-01_ is a bare-metal x86_64 server that is used to host different virtual machines.
The host device is a https://www.bee-link.com/products/beelink-eqi13-pro[Beelink EQi13 Pro] with an Intel Core i7 13620H, 32GB of RAM, and a 1TB SSD.

== Bootstrapping

If the minipc already has a linux distribution installed that https://man7.org/linux/man-pages/man8/kexec.8.html[supports kexec], you can skip the following step.
Prepare the link:../../installer[NixOS Installer] on a USB stick.
Insert the USB stick into the minipc and connect the minipc to a monitor and keyboard.
After entering the BIOS either change the boot priority to boot from the USB media first, or boot directly into the USB media without changing the options.

Ensure the minipc is reachable via SSH (in this example it is reachable as `nixos-installer.fritz.box`).
Use {url-nixos-anywhere}[`nixos-anywhere`] to install the NixOS configuration.

.Install the NixOS configuration with {url-nixos-anywhere}[`nixos-anywhere`].
[source,console]
----
$ SSHPASS=root nix run nixpkgs#nixos-anywhere -- --flake '.#hl-vhost-x-01' -L --target-host root@192.168.178.130 --env-password --generate-hardware-config nixos-facter ./facter.json
----

Set a disk encryption password when prompted.
This does not need to have high entropy - after the first boot we will replace it with yubikey authentication.
After the installation is done,
unlock the disk via SSH

.Unlock the disk encryption after the reboot
[source,console]
----
$ ssh root@192.168.178.130 -p 2222
----

After unlocking the disk, SSH into `hl-vhost-x-01` and `sudo su` to `root`.
We are going to enroll a recovery key and a yubikey with `systemd-cryptenroll` and remove the low entropy passphrase.

.Enroll the Yubikey and a recovery key for disk decryption
[source,console]
----
hl-vhost-x-01 $ systemd-cryptenroll /dev/nvme0n1p4
hl-vhost-x-01 $ systemd-cryptenroll /dev/nvme0n1p4 --recovery-key
hl-vhost-x-01 $ systemd-cryptenroll /dev/nvme0n1p4 --fido2-device=auto --fido2-with-client-pin=false --fido2-with-user-presence=true --fido2-with-user-verification=false --fido2-credential-algorithm=eddsa
hl-vhost-x-01 $ systemd-cryptenroll /dev/nvme0n1p4 --wipe-slot=password
----

== Updating the Configuration

To update the configuration from a remote machine, you can use {url-deploy-rs}[`deploy-rs`].

.Update the NixOS configuration with {url-deploy-rs}[`deploy-rs`].
[source,console]
----
$ nix run nixpkgs#deploy-rs -- '.#hl-vhost-x-01'
----
